# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 02 - Workflow Events
on: workflow_dispatch

  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "${{ github.event_name }}"
  echo-2:
    runs-on: ubuntu-latest
    steps:
      - name: Show scheduled trigger
        run: echo "Mensagem disparada pelo cron"